version: '2'
services:
  facetious:
    image: tsears:facetious
    environment:
      MODE: 'dev'
    env_file:
      - ../.env.list
    volumes:
      - ..:/app
    entrypoint:
      - /bin/bash
      - -c
      - "cd /var/app && npm start"
