version: '2'
services:
  facetious:
    image: tsears:facetious
    environment:
      MODE: 'dev'
    env_file:
      - ../.env.list
    volumes:
      - ../:/var/app:ro
    entrypoint:
      - /bin/bash
      - -c
      - "cd /var/app && ls && npm run dev"
